#!/bin/bash

mode="git"
cwd=$(pwd)
# set config for Git repositories as configured in git_repos.list
path=$HOME/.sync-conf/git_repos.list
IFS=' '


if [ -f $path ]; then
	while read line; do
		# ignore comments or empty line
		if [[ "$line" == \#* || "$line" == "" ]]; then
			continue
		fi
		# first cut out all arguments that might be quoted
		name=$(cut -s -d '"' -f2 <<< "$line")
		if [ -z "$name" ]; then
			name=$(cut -d ' ' -f2 <<< "$line")
			# delete second field
			line=$(cut -d ' ' -f1,3- <<< "$line")
		else
			# delete second field
			line=$(sed 's/"[^"]*"//' <<< "$line")
		fi
		read repo_path email <<< "$line"
		repo_path="${repo_path/#\~/$HOME}"
		cd $repo_path
		git config user.name "${name}"
		git config user.email $email
	done < $path
else
	echo "The file git_repos.list cannot be found. Aborting."
	exit 1
fi


