#!/bin/bash

action=$1
shift
force=$1
shift
ssh_login=$1
shift
local_path=$1
shift
server_path=$1
shift
profile=$1

local_path="${local_path/#\~/$HOME}"
mkdir ~/.unison &> /dev/null

if [ -z "$profile" ]; then
  #if no unison profile chose, use default profile
  profile=sjm_default
fi

if [[ "$profile" != *\.prf ]]; then
  # get profile file name by appending suffix
  profile_file=$profile'.prf'
else
  profile_file=$profile
  profile=${profile/%\.prf}
fi

template_dir=unison-templates
if [ -f $DIR/$template_dir/$profile_file ]; then
  template_path=$DIR/$template_dir/$profile_file
else
  echo "${confdir}/${template_dir}/${profile_file}"
  if [ -f $confdir/$template_dir/$profile_file ]; then
    template_path=$confdir/$template_dir/$profile_file
  else
    echo "Unison template file ${profile_file} cannot be found."
    exit 1
  fi
fi

remote_path=$server_path

#create directories, locally and remotely
if [ ! -d $local_path ]; then
  mkdir -p $local_path
fi
echo "unison sync ${local_path}"

# create path on remote machine for syncing
ssh $ssh_login "mkdir -p ${remote_path}"

#server_path must contain ssh login
server_path="ssh://${ssh_login}/${server_path}"

# prepare profile for the unison sync
# copy the right profile template and replace the parameters

sed -e "s|@local_path@|${local_path}|g" -e "s|@server_path@|${server_path}|g" $template_path >  ~/.unison/$profile_file
# finally sync files with the profile

if [ $force = 1 ]; then
  if [ $action = 'push' ];  then
    unison $profile -force  "$local_path"
  fi
  if [ $action = 'pull' ]; then
    unison $profile -force  "$server_path"
  fi
else 
  unison -auto $profile
fi


# clean up
rm ~/.unison/$profile_file
echo -e "\n"
